version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  base10-foo-bar:
    docker:
      - image: cypress/base:10
    environment:
            OktaUserName: $OktaUserName
            OktaUserPassword: $OktaUserPassword
workflows:
  build:
    jobs:
      - cypress/run:
          start: npm start
          wait-on: 'http://localhost:3000'
